

# This file was *autogenerated* from the file find_irreducible.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_128 = Integer(128); _sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4)# degree=4
# R = GF(2)['x']
# for p in R.polynomials(degree):
#      if p.is_irreducible():
#          print(p)


F = GF(_sage_const_2 **_sage_const_128 , modulus=x**_sage_const_128  + x**_sage_const_7  + x**_sage_const_2  + x + _sage_const_1 , names=('a',)); (a,) = F._first_ngens(1)
R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)

def irreducible_degree_4():
    while True:
        f = x**_sage_const_4  + sum([F.random_element() * x**i for i in range(_sage_const_4 )])
        
        if f.is_irreducible():
            return f

irreducible_poly = irreducible_degree_4()
print(irreducible_poly)

