

# This file was *autogenerated* from the file rain_hash_check poly.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_128 = Integer(128); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_123 = Integer(123); _sage_const_1 = Integer(1)# Step 1: Define the base field GF(2^128)
F = GF(_sage_const_2 **_sage_const_128 , name='a', modulus="primitive", names=('a',)); (a,) = F._first_ngens(1)# primitive default irreducible

# Step 2: Define the polynomial ring over GF(2^128)
R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)

# Step 3: Define the input polynomials with symbolic coefficients
# (you can assign actual values to a_i and b_i instead of using variables)
a0, a1, a2, a3 = var('a0 a1 a2 a3')
b0, b1, b2, b3 = var('b0 b1 b2 b3')

# Define the polynomials (replace vars with actual GF(2^128) elements if desired)
A = a3*x**_sage_const_3  + a2*x**_sage_const_2  + a1*x + a0
B = b3*x**_sage_const_3  + b2*x**_sage_const_2  + b1*x + b0

# Step 4: Multiply polynomials
P = A * B

# Step 5: Define the reduction polynomial: x^4 + a^123 * x^2 + x + 1
mod_poly = x**_sage_const_4  + a**_sage_const_123  * x**_sage_const_2  + x + _sage_const_1 

# Step 6: Reduce the product modulo the irreducible polynomial
Q = P % mod_poly

# Output the result
print("Resultant reduced polynomial Q(x):")
show(Q)

