

# This file was *autogenerated* from the file ./script_4_to_256.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_256 = Integer(256); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_32 = Integer(32); _sage_const_8 = Integer(8); _sage_const_0xff = Integer(0xff)
R = GF(_sage_const_2 )['x']; (x,) = R._first_ngens(1)
E = GF(_sage_const_2 **_sage_const_4 , modulus=x**_sage_const_4  + x + _sage_const_1 , names=('y',)); (y,) = E._first_ngens(1)
F = GF(_sage_const_2 **_sage_const_256 , modulus=x**_sage_const_256  + x**_sage_const_10  + x**_sage_const_5  + x**_sage_const_2  + _sage_const_1 , names=('y',)); (y,) = F._first_ngens(1)

mod_256 = x**_sage_const_256  + x**_sage_const_10  + x**_sage_const_5  + x**_sage_const_2  + _sage_const_1 

P = PolynomialRing(F, names=('z',)); (z,) = P._first_ngens(1)
f = z**_sage_const_4  + z + _sage_const_1 



# print(f.roots()[0])
# poly = f.roots()[0][0].polynomial()
# int_value = sum([int(c) << i for i, c in enumerate(poly.coefficients(sparse=False))])
# print(f"0x{int_value:032x}")


print(f.roots()[_sage_const_0 ])
poly = f.roots()[_sage_const_0 ][_sage_const_0 ].polynomial()

# int_value = sum([int(c) << i for i, c in enumerate(poly.coefficients(sparse=False))])
# print(f"0x{int_value:032x}")

poly_over_GF2 = R(poly)
for i in range(_sage_const_1 ,_sage_const_4 ):
    poly_pow = (poly_over_GF2**i) % mod_256
    int_value = sum([int(c) << i for i, c in enumerate(poly_pow.coefficients(sparse=False))])
    print(f"0x{int_value:064x}")
    t = "{"
    for j in range(_sage_const_0 ,_sage_const_32 ):
        t += f"0x{((int_value >> j*_sage_const_8 ) & _sage_const_0xff ):02x}" + ", "
    t += "}"
    print(t)

#print(hex(Integer(f.roots()[0][0].polynomial().integer_representation())))

#if False:
#    K.<x> = GF(2^4, modulus= X^4+X+1)
#    F = GF(2^128, 'y', modulus = X^128 + X^7 + X^2 + X + 1)
#    print(F, F.modulus())
#    print(F.gens())
#    H = Hom(K, F)
#    morph = H.list()[0]
#    g = morph.im_gens()[0]
#    print(morph)
#    y^14 + y^8 + y^7 + y^6 + y^3 + y^2 + 1
#    y^14 + y^8 + y^7 + y^6 + y^3 + y^2 + 1
#    y^14 + y^13 + y^11 + y^7 + 1

